CREATE DATABASE ranger DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE USER 'ranger'@'%' IDENTIFIED BY '@MYSQL_RANGER_DB_USER_PASSWORD@';
GRANT ALL PRIVILEGES ON ranger.* TO 'ranger'@'%';

FLUSH PRIVILEGES;